apiVersion: v1
kind: Service
metadata:
  name: sample
  namespace: sample
  labels:
    run: sample
spec:
  type: NodePort
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    run: sample